"""add average_rating and total_reviews to products

Revision ID: 45a64ff08dd3
Revises: 69044fd674d3
Create Date: 2026-05-16 14:01:18.562905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a64ff08dd3'
down_revision: Union[str, None] = '69044fd674d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('orders', 'discount_amount',
    #           existing_type=sa.DOUBLE_PRECISION(precision=53),
    #          nullable=False)
    op.add_column('products', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('total_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_reviews')
    op.drop_column('products', 'average_rating')
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
