"""add voucher fields to orders

Revision ID: 69044fd674d3
Revises: 8f295c701242
Create Date: 2026-05-16 13:04:31.945558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69044fd674d3'
down_revision: Union[str, None] = '8f295c701242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('applied_voucher_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'vouchers', ['applied_voucher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'applied_voucher_id')
    # ### end Alembic commands ###
