"""add soft delete to address cart wishlist order payment

Revision ID: 6c9a9cabb9b1
Revises: 45a64ff08dd3
Create Date: 2026-05-16 14:15:53.482334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9a9cabb9b1'
down_revision: Union[str, None] = '45a64ff08dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('orders', 'discount_amount',
    #           existing_type=sa.DOUBLE_PRECISION(precision=53),
    #           nullable=False)
    #op.alter_column('products', 'average_rating',
    #           existing_type=sa.DOUBLE_PRECISION(precision=53),
    #           nullable=False)
    #op.alter_column('products', 'total_reviews',
    #           existing_type=sa.INTEGER(),
    #           nullable=False)
    # ### end Alembic commands ###
    pass 

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('products', 'total_reviews',
    #           existing_type=sa.INTEGER(),
    #           nullable=True)
    #op.alter_column('products', 'average_rating',
    #           existing_type=sa.DOUBLE_PRECISION(precision=53),
    #           nullable=True)
    #op.alter_column('orders', 'discount_amount',
    #           existing_type=sa.DOUBLE_PRECISION(precision=53),
    #           nullable=True)
    # ### end Alembic commands ###
    pass 